version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  user-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'user-db'
    ports:
      - "3308:3306"
    volumes:
      - user-volume:/var/lib/mysql
    networks:
      - my_network

  device-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'device-db'
    ports:
      - "3307:3306" 
    volumes:
      - device-volume:/var/lib/mysql
    networks:
      - my_network

  monitoring-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'monitoring-db'
    ports:
      - "3309:3306"
    volumes:
      - monitoring-volume:/var/lib/mysql
    networks:
      - my_network

  device-backend:
    build: back/device
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=device-db
    depends_on:
      - device-db
    networks:
      - my_network

  user-backend:
    build: back/user
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=user-db
      - DEVICE_BACKEND_IP=device-backend
      - DEVICE_BACKEND_PORT=8081
    depends_on:
      - user-db
    networks:
      - my_network

  monitoring-backend:
    build: back/monitoring
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=monitoring-db
    depends_on:
      - monitoring-db
    networks:
      - my_network
    
  chat-backend:
    build: back/chat
    ports:
      - "8083:8083"
    networks:
      - my_network

  react-frontend:
    build: front/my-app
    ports:
      - "3000:80"
  
volumes:
  user-volume:
  device-volume:
  monitoring-volume:


